server:
  port: 8081
# JPA
spring:
  application:
    name: ml_pet_insurance
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: azure-db-admin@azure-conestoga
    url: jdbc:sqlserver://azure-conestoga.database.windows.net:1433;database=pet-insurance-db;user=azure-db-admin@azure-conestoga;password=gxRjhHgXnRX5Aa#q;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    password: gxRjhHgXnRX5Aa#q
#    password: root
#    url: jdbc:mysql://localhost:3306/ml_pet_insurance_v2?createDatabaseIfNotExist=true
#    username: root

    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 10
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true






