server:
  port: 8081
# JPA
spring:
  jpa:
    generate-ddl: true
  properties:
  hibernate:
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  ddl-auto: create
  # MySql
  datasource:
    url: jdbc:mysql://localhost:3306/ml_pet_insurance_v2
    username: root
    password: root
    # Connection Pool
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 10
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true





